imgurmedia_entity_imgur.settings:
  type: config_object
  label: 'Media entity Imgur settings'
  mapping:
    local_images:
      type: string
      label: 'Base folder for thumbnails'

media_entity.bundle.type.imgur:
  type: mapping
  label: 'Imgur type configuration'
  mapping:
    source_field:
      type: string
      label: 'Field with embed code/URL'
    use_imgur_api:
      type: boolean
      label: 'Use Imgur API or not'
    client_id:
      type: string
      label: 'Field with client id'

field.formatter.settings.imgur_embed:
  type: mapping
  label: 'Image field display format settings'
  mapping:
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
